name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-east1
  SERVICE_NAME: line-bot-service
  REGISTRY: asia-east1-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        service_account: '${{ secrets.GCP_SA_EMAIL }}'
        create_credentials_file: true
        export_environment_variables: true
        cleanup_credentials: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Enable Essential APIs
      run: |
        echo "Enabling Cloud Resource Manager API..."
        gcloud services enable cloudresourcemanager.googleapis.com || true
        echo "Enabling IAM API..."
        gcloud services enable iam.googleapis.com || true
        echo "Waiting for API activation to propagate..."
        sleep 30

    - name: Verify Authentication and Project Access
      run: |
        echo "Verifying authentication..."
        gcloud auth list
        
        echo "Checking project configuration..."
        gcloud config list project
        
        echo "Testing project access..."
        gcloud projects describe $PROJECT_ID || echo "Limited project access, continuing..."
        
        echo "Checking service account permissions..."
        gcloud iam service-accounts get-iam-policy ${{ secrets.GCP_SA_EMAIL }} \
          --project $PROJECT_ID || echo "Limited IAM access, continuing..."

    - name: Enable Required APIs
      run: |
        apis=(
          "cloudresourcemanager.googleapis.com"
          "artifactregistry.googleapis.com"
          "run.googleapis.com"
          "containerregistry.googleapis.com"
          "iam.googleapis.com"
        )
        
        for api in "${apis[@]}"; do
          echo "Enabling $api..."
          gcloud services enable $api || echo "Failed to enable $api, continuing..."
          sleep 5
        done

    - name: Authorize Docker push
      run: |
        gcloud auth configure-docker $REGISTRY

    - name: Create Artifact Registry Repository
      run: |
        gcloud artifacts repositories create $SERVICE_NAME \
          --repository-format=docker \
          --location=$REGION \
          --project=$PROJECT_ID || true

    - name: Build and Push Container
      run: |
        docker build -t $REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} .
        docker push $REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGISTRY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:${{ github.sha }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          --set-env-vars "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" 